import type { ThemeTokens } from "./types";

export const theme: ThemeTokens = {
  colors: {
    background: "#040818",
    backgroundElevated: "#081126",
    surface: "#101C3A",
    surfaceAlt: "#16274D",
    border: "#2F4C7F",
    textPrimary: "#F3F8FF",
    textSecondary: "#AFC4EC",
    textMuted: "#7C96C8",
    accentCyan: "#36E5FF",
    accentGreen: "#52F0CB",
    accentPurple: "#9E6DFF",
    warning: "#F9C74F",
    danger: "#F87171",
    success: "#4ADE80",
  },
  typography: {
    display: {
      fontSize: 30,
      lineHeight: 36,
      fontWeight: "800",
      fontFamily: "Sora_800ExtraBold",
    },
    title: {
      fontSize: 22,
      lineHeight: 28,
      fontWeight: "700",
      fontFamily: "Sora_700Bold",
    },
    body: {
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "400",
      fontFamily: "Manrope_400Regular",
    },
    caption: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: "600",
      fontFamily: "Manrope_600SemiBold",
    },
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
  },
  elevation: {
    card: {
      shadowColor: "#000000",
      shadowOpacity: 0.34,
      shadowRadius: 22,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    glowCyan: {
      shadowColor: "#36E5FF",
      shadowOpacity: 0.5,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 0 },
      elevation: 10,
    },
    glowGreen: {
      shadowColor: "#52F0CB",
      shadowOpacity: 0.42,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 0 },
      elevation: 10,
    },
    glowPurple: {
      shadowColor: "#9E6DFF",
      shadowOpacity: 0.44,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 0 },
      elevation: 10,
    },
  },
  motion: {
    fastMs: 120,
    normalMs: 220,
  },
};
